services:
  redis:
    image: redis:7-alpine
    container_name: dnd_redis
    ports:
      - "6379:6379"
    networks:
      - dnd_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dnd_backend
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=supersecretdevkey
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - WIPE_DB_ON_RESTART=true
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app/backend
      - dnd_db:/app/instance
    depends_on:
      - redis
    networks:
      - dnd_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dnd_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - dnd_network

networks:
  dnd_network:
    driver: bridge

volumes:
  dnd_db:
    driver: local
