services:
  - type: keyvalue
    name: dnd-redis
    region: frankfurt
    plan: free
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  - type: web
    name: dnd-backend
    region: frankfurt
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /api/docs
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: WIPE_DB_ON_RESTART
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: dnd-database
          property: connectionString
      - key: CACHE_TYPE
        value: RedisCache
      - key: CACHE_REDIS_URL
        fromService:
          name: dnd-redis
          type: keyvalue
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: dnd-redis
          type: keyvalue
          property: connectionString

  - type: web
    name: dungeons-and-databases
    region: frankfurt
    plan: free
    runtime: docker
    dockerContext: frontend
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: BACKEND_API_BASE
        value: https://dnd-backend-6ymc.onrender.com/api
    healthCheckPath: /

databases:
  - name: dnd-database
    region: frankfurt
    plan: free
