version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dnd_backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0
    networks:
      - dnd_network

  frontend:
    build:
      context: ./Dnd
      dockerfile: Dockerfile
    container_name: dnd_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - dnd_network
    environment:
      - VITE_API_BASE=http://localhost:5000/api

networks:
  dnd_network:
    driver: bridge
