@startuml architecture
title Dungeons and Databases System Architecture
left to right direction
skinparam shadowing false
skinparam componentStyle rectangle
'skinparam packageStyle rectangle
'skinparam linetype polyline
skinparam DefaultFontSize 20
skinparam TitleFontSize 25

actor "User browser" as user

package "Locally hosted Docker containers" {

    package "Frontend Container" {
        component "Nginx proxy" as nginx
        component "HTML+JS app" as frontend
    }
    
    package "Backend services" {
        component "Backend container\nFlask API" as backend
        component "Redis container\ncache" as redis
        database "SQLite\ndatabase" as sqlite
        component "Adminer container\ndatabase UI" as adminer
    }
}

user --> nginx : browse app

nginx -> frontend : Static files

nginx -u-> backend : API calls
nginx --> adminer : /admin/adminer
nginx --> backend : /admin/dashboard
adminer --> sqlite : manage database
sqlite <-u-> backend : read/write data
redis <-u-> backend : cached data

adminer -l[hidden]-> backend

@enduml