name: Test and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run tests and generate coverage report
        run: |
            docker compose --profile test run --rm backend-tests && \
            docker compose --profile test run --rm --entrypoint "rm /app/htmlcov/.gitignore" backend-tests

      - name: Upload coverage report to Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./htmlcov
          allow_empty_commit: true
          force_orphan: true

      - name: Push to Production Branch
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git push origin main:production --force