name: Tests and Coverage

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tests-with-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run tests and generate coverage report
        run: |
            docker compose --profile test run --rm backend-tests
            docker compose --profile test run --rm --entrypoint "rm /app/htmlcov/.gitignore" backend-tests

      - name: Upload coverage report to Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./htmlcov
          allow_empty_commit: true
          force_orphan: true